# Generated by Django 2.2 on 2019-04-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_Assistant',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_Manager',
        ),
    ]
